let userChoice;

// while(true)
// {
    userChoice = +prompt("Please select the task (1 - 10)");

    switch(userChoice)
    {
        case 1: Task1();
        break;

        case 2: Task2();
        break;

        case 3: Task3();
        break;

        case 4: Task4();
        break;

        case 5: Task5();
        break;

        case 6: Task6();
        break;

        case 7: Task7();
        break;

        case 8: Task8();
        break;

        case 9: Task9();
        break;

        case 10: Task10();
        break;
    }
// }

function Task1()
{
    let digit = prompt("Please enter your digit");
    alert(`Second power of digit ${digit} is ${digit**2}!`);

}

function Task2()
{
    alert("Hello from Task 2!");
}

function Task3()
{
    
}

function Task4()
{
    
}

function Task5()
{
    
}

function Task6()
{
    
}

function Task7()
{
    
}

function Task8()
{
    
}

function Task9()
{
    
}

function Task10()
{
    
}